apiVersion: v1
kind: Pod
metadata:
  name: mypod123
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: /var/www/html
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: 'research-pvc' 
